### ISSUE TITLE
Falta completar

### ISSUE THREAD

**Issue by developerspro** [developerspro/pra2023#1]
https://github.com/developerspro/pra2023/blob/2b5956341121f3a57842c3a9a8e10c366644d11b/adicao.txt#L1
@SamuelLopes999 
@Alexsander-ETEC

**Comment by allekstat** [comment]
ta certo

**Comment by Gabrielulululu** [comment]
eu quero a minha mãe :(

**Comment by Gabrielberato** [comment]
slv slv

**Comment by developerspro** [comment]
ok

**Comment by Kawanrv** [comment]
libera nois
